reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group

  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - pushkarj
    supply-chain-security-reviewers:
    whitepaper-reviewers:
      - pushkarj
    assessments-reviewers:

files:
  # Keys are glob expressions.
  # You can assign groups defined above as well as GitHub usernames.
  '**.**':
    - repository-owners # group
  'security-whitepaper/**':
    - whitepaper-reviewers # group
  'supply-chain-security/**':
    - supply-chain-security-reviewers #group
  '.github/**':
    - repository-owners # group

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
    - NOT READY FOR REVIEW
  enable_group_assignment: false

  # Randomly pick reviewers up to this number.
  # Do not set this option if you'd like to assign all matching reviewers.
  number_of_reviewers: 3